name: "Generate Document"
on:
  push:
    branches: [main]
defaults:
  run:
    working-directory: .
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tex To PDF
        uses: ./actions/pdflatex
        env:
          OUT_DIR: public
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: public/
  distribute-project:
    name: Distribute PDF to GitHub Releases
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
      - name: Download PDF Content
        uses: actions/download-artifact@v2
        with:
          name: files
      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}-${{ steps.date.outputs.date }}
          release_name: Release ${{ github.run_number }}
      - name: Upload PDF to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: main.pdf
          asset_name: cv_dominic_bean_without_profile_and_pid.pdf
          asset_content_type: application/pdf
